In [1]:
from kmds.utils.config_reader import get_config
from minio import Minio

In [2]:
s3_cfg = get_config("./play_minio_cfg.yaml")

In [3]:
HOST_URL = s3_cfg["HOST_URL"]

ACCESS_KEY = s3_cfg["ACCESS_KEY"]
SECRET_KEY = s3_cfg["SECRET_KEY"]
BUCKET_NAME = s3_cfg["BUCKET_NAME"]

In [4]:
client = Minio(endpoint=HOST_URL, access_key=ACCESS_KEY, secret_key=SECRET_KEY, secure=True)

In [5]:
import pandas as pd
from io import StringIO
object_name = "incident_event_log_02.csv"
obj = client.get_object(BUCKET_NAME, object_name)
data = obj.data

In [6]:
s = str(data,'utf-8')
data = StringIO(s)
df = pd.read_csv(data)

/var/folders/fb/t_m5qpcj6qq85rvkh73vbxh40000gn/T/ipykernel_82352/2505608108.py:3: DtypeWarning: Columns (19,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data)

In [7]:
df

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141707,INC0120835,Closed,False,1,0,4,True,Caller 116,Opened by 12,16/2/2017 09:09,...,True,Do Not Notify,NaN,NaN,NaN,NaN,code 9,Resolved by 9,16/2/2017 09:53,16/2/2017 09:53
141708,INC0121064,Active,True,0,0,0,True,Caller 116,Opened by 12,16/2/2017 14:17,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141709,INC0121064,Active,True,1,0,1,True,Caller 116,Opened by 12,16/2/2017 14:17,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141710,INC0121064,Resolved,True,1,0,2,True,Caller 116,Opened by 12,16/2/2017 14:17,...,True,Do Not Notify,NaN,NaN,NaN,NaN,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141711,INC0121064,Closed,False,1,0,3,True,Caller 116,Opened by 12,16/2/2017 14:17,...,True,Do Not Notify,NaN,NaN,NaN,NaN,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38